# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="shekeriev/centos-7-64-minimal"
    web.vm.hostname = "web.sulab.local"
    web.vm.network "private_network", ip: "192.168.82.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "webu" do |webu|
    webu.vm.box="ubuntu/trusty64"
    webu.vm.hostname = "webu.sulab.local"
    webu.vm.network "private_network", ip: "192.168.82.105"
    webu.vm.network "forwarded_port", guest: 80, host: 8081
  end
  
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-7-64-minimal"
    db.vm.hostname = "db.sulab.local"
    db.vm.network "private_network", ip: "192.168.82.101"
  end

  config.vm.define "clnt" do |clnt|
    clnt.vm.box = "shekeriev/centos-7-64-minimal"
    clnt.vm.hostname = "clnt.sulab.local"
    clnt.vm.network "private_network", ip: "192.168.82.102"
  end
 
end
