DECLARE @DBName VARCHAR(255)
DECLARE @SQL NVARCHAR(255)

DECLARE FULLRECOVERY CURSOR FOR   
SELECT name  
FROM sys.databases WHERE database_id > 4 and recovery_model_desc = 'SIMPLE'

OPEN FULLRECOVERY 
FETCH NEXT FROM FULLRECOVERY INTO @DBName 
WHILE @@FETCH_STATUS = 0 
BEGIN
    SET @SQL = 'ALTER DATABASE [' + @DBName + '] SET RECOVERY FULL' 
    PRINT @SQL 
    EXECUTE sp_executesql @sql 
    FETCH next FROM FULLRECOVERY INTO @DBName 

END 

CLOSE FULLRECOVERY 
DEALLOCATE FULLRECOVERY 