apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-demo-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: auto-demo
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auto-demo
    spec:
      containers:
      - name: auto-demo-container
        image: herrnikolov/dof:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: auto-demo-svc
  labels:
    app: auto-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
      app: auto-demo
