FROM busybox
LABEL version="1.0" description="Hello World image built for a DevOps Basics course Module 2 at SoftUni" maintainer="dimitar@zahariev.pro"
ADD welcome-dob-oct-17.sh /
CMD ["./welcome-dob-oct-17.sh"]
