apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis-host
    image: kubernetes/redis:v1
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
