apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-alt.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web-page
  name: web-page
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-page
    spec:
      containers:
      - image: shekeriev/docker-and-jenkins:latest
        name: web-page
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
