# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "dobweb" do |dobweb|
    dobweb.vm.box="shekeriev/centos-7-64-minimal"
    dobweb.vm.hostname = "dbo-web.sulab.local"
    dobweb.vm.network "private_network", ip: "192.168.81.100"
    dobweb.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    dobweb.vm.synced_folder "vagrant/web/", "/vagrant"
    dobweb.vm.provision "shell", inline: <<EOS
echo "* Add hosts ..."
echo "192.168.81.100 dob-web.sulab.local dob-web" >> /etc/hosts
echo "192.168.81.101 dob-db.sulab.local dob-db" >> /etc/hosts

echo "* Install Software ..."
sudo yum update
sudo yum install -y httpd php php-mysql git

echo "* Start HTTP ..."
sudo systemctl enable httpd
sudo systemctl start httpd

echo "* Stop firewall ..."
sudo systemctl stop firewalld
sudo systemctl disable firewalld

echo "* Copy web site files to /var/www/html/ ..."
cp /vagrant/* /var/www/html

echo "* Allow HTTPD to make netork connections ..."
sudo setsebool -P httpd_can_network_connect=1
EOS
  end

  config.vm.define "dobdb" do |dobdb|
    dobdb.vm.box="shekeriev/centos-7-64-minimal"
    dobdb.vm.hostname = "dbo-db.sulab.local"
    dobdb.vm.network "private_network", ip: "192.168.81.101"
    dobdb.vm.synced_folder "vagrant/db/", "/vagrant"
    dobdb.vm.provision "shell", inline: <<EOS
echo "* Add hosts ..."
echo "192.168.81.100 dob-web.sulab.local dob-web" >> /etc/hosts
echo "192.168.81.101 dob-db.sulab.local dob-db" >> /etc/hosts

echo "* Install Software ..."
sudo yum update
sudo yum install -y mariadb mariadb-server

echo "* Start HTTP ..."
sudo systemctl enable mariadb
sudo systemctl start mariadb

echo "* Stop firewall ..."
sudo systemctl stop firewalld
sudo systemctl disable firewalld

echo "* Create and load the database ..."
mysql -u root < /vagrant/db_setup.sql
EOS
  end

end
 
